repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        # ensure the hook env actually installs this version (has GitLabTokenDetector)
        additional_dependencies:
          - "detect-secrets==1.5.0"
        args:
          - --baseline
          - ".secrets.baseline"
