services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports: ["9000:9000", "9001:9001"]
    volumes: [minio:/data]

  backend:
    build: ./apps/backend
    env_file: .env
    depends_on: [postgres, redis, minio]
    ports: ["8000:8000"]
    volumes:
      - ../data:/app/data

  worker:
    build: ./apps/worker
    env_file: .env
    depends_on: [redis, backend]
    volumes:
      - ../data:/app/data

volumes:
  pgdata:
  minio:
